name: Hello From main

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: echo event name
        run: echo $github.events
      
